name: my_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  http: ^1.2.1
  flutter_lints: ^3.0.0
  image_picker: 1.1.1
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.5
  meta: ^1.11.0
  intl: ^0.19.0
  flutter_secure_storage: ^8.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
    - assets/images/img_memoji_124x124.png
    - assets/images/profile.png
    - assets/images/bg.jpeg
    - assets/images/brainbox.jpeg
    - assets/images/bio.jpg
    - assets/images/phy.jpg
    - assets/images/che.jpg
    - assets/images/math.jpg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700